version: '3.8'

services:
    bankaccount-api:
        container_name: bankaccount-api
        build: 
            context: .
            dockerfile: BankAccountServiceAPI/Dockerfile
        ports:
            - "8000:80"
    
    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:22.0.5
        command: start-dev
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            # Для внешнего доступа (из браузера)
            - KC_HOSTNAME-keycloak
            # Для внутреннего общения и "штампов" в токенах
            - KC_HOSTNAME_URL=http://localhost:8080
            - KC_HOSTNAME_STRICT=false
        ports:
            - "8080:8080"
        
    

