version: '3.8'

services:
    bankaccount-api:
        container_name: bankaccount-api
        build: 
            context: .
            dockerfile: BankAccountServiceAPI/Dockerfile
        ports:
            - "8000:80"
    
    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:latest
        command: start-dev
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        ports:
            - "8080:8080"
        
    

